### ISSUE TITLE
Remaining TODO's from #15

### ISSUE THREAD

**Issue by jamestalmage** [urish/firebase-server#27]
Originally posted in #15, but that is closed, reposting here so we don't lose track.

**Mirror Server Error Responses for `authWithCustomToken` in the following Scenarios**

(current thought is not to pursue these)
- [ ] Invalid JWT - it is not a valid JWT token
- [ ] Invalid Signature - wrong secret
- [ ] Too Early - the server time is before notBefore
- [ ] Too Late - the server time is after expires
- [ ] No `uid` property - `firebase-token-generator` the docs say you are required to provide a uid as part of authData. That is a firebase specific requirement (it will not be validated by a generic JWT library like jwt-simple).
- [ ] No `iat` property - I do not actually know if this is required, but  `firebase-token-generator` automatically adds it (it is the time the token was created).

**Mirror Server Action as Token Reaches Expiration**

We need to figure out what happens when a token expires. 
- [ ] Are you just switched to "unauthenticated" mode? 
- [ ] Is a message sent to idle clients? 
- [ ] How is ref.onAuth() triggered as your token expires?

**Additional Items / Housekeeping**
- [x] Update documentation
- [x] more descriptive methods: `setSecret => setAuthSecret`
- [ ] option to disable `expires` / `notBefore` checks
- [x] option to disable token signature check (`setSecret(null)`)

**Comment by urish** [comment]
Once the documentation bit and `setAuthSecret` is done, I will release the current code as 0.5.0
